[package]
name = "pg_deparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pg_query = "0.8.2"
thiserror = "1.0.31"

[dev-dependencies]
regex = "1.6.0"
