[package]
name = "pg_deparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pg_query = "0.8.2"

[dev-dependencies]
glob = "0.3.1"
