[package]
name = "pg_print"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
pg_query = "0.8.2"

[dev-dependencies]
insta = "1.34.0"
