use crate::fmt::Printer;
use pg_query::NodeEnum;

#[derive(Debug)]
pub struct RawStmt<'a> {
    pub stmt: &'a NodeEnum,
}

impl Printer {
    pub fn stmt(&mut self, n: &RawStmt) {
        match &n.stmt {
            NodeEnum::InsertStmt(_) => todo!(),
            NodeEnum::DeleteStmt(_) => todo!(),
            NodeEnum::UpdateStmt(_) => todo!(),
            NodeEnum::MergeStmt(_) => todo!(),
            NodeEnum::SelectStmt(n) => self.select_stmt(n),
            NodeEnum::ReturnStmt(_) => todo!(),
            NodeEnum::PlassignStmt(_) => todo!(),
            NodeEnum::AlterTableStmt(_) => todo!(),
            NodeEnum::AlterDomainStmt(_) => todo!(),
            NodeEnum::SetOperationStmt(_) => todo!(),
            NodeEnum::GrantStmt(n) => self.grant_stmt(n),
            NodeEnum::GrantRoleStmt(_) => todo!(),
            NodeEnum::AlterDefaultPrivilegesStmt(_) => todo!(),
            NodeEnum::ClosePortalStmt(_) => todo!(),
            NodeEnum::ClusterStmt(_) => todo!(),
            NodeEnum::CopyStmt(_) => todo!(),
            NodeEnum::CreateStmt(n) => self.create_stmt(n),
            NodeEnum::DefineStmt(n) => self.define_stmt(n),
            NodeEnum::DropStmt(_) => todo!(),
            NodeEnum::TruncateStmt(_) => todo!(),
            NodeEnum::CommentStmt(_) => todo!(),
            NodeEnum::FetchStmt(_) => todo!(),
            NodeEnum::IndexStmt(n) => self.index_stmt(n),
            NodeEnum::CreateFunctionStmt(n) => self.create_function_stmt(n),
            NodeEnum::AlterFunctionStmt(_) => todo!(),
            NodeEnum::DoStmt(_) => todo!(),
            NodeEnum::RenameStmt(_) => todo!(),
            NodeEnum::RuleStmt(_) => todo!(),
            NodeEnum::NotifyStmt(_) => todo!(),
            NodeEnum::ListenStmt(_) => todo!(),
            NodeEnum::UnlistenStmt(_) => todo!(),
            NodeEnum::TransactionStmt(_) => todo!(),
            NodeEnum::ViewStmt(n) => self.view_stmt(n),
            NodeEnum::LoadStmt(_) => todo!(),
            NodeEnum::CreateDomainStmt(n) => self.create_domain_stmt(n),
            NodeEnum::CreatedbStmt(_) => todo!(),
            NodeEnum::DropdbStmt(_) => todo!(),
            NodeEnum::VacuumStmt(_) => todo!(),
            NodeEnum::ExplainStmt(_) => todo!(),
            NodeEnum::CreateTableAsStmt(n) => self.create_table_as_stmt(n),
            NodeEnum::CreateSeqStmt(_) => todo!(),
            NodeEnum::AlterSeqStmt(_) => todo!(),
            NodeEnum::VariableSetStmt(_) => todo!(),
            NodeEnum::VariableShowStmt(_) => todo!(),
            NodeEnum::DiscardStmt(_) => todo!(),
            NodeEnum::CreateTrigStmt(n) => self.create_trig_stmt(n),
            NodeEnum::CreatePlangStmt(_) => todo!(),
            NodeEnum::CreateRoleStmt(_) => todo!(),
            NodeEnum::AlterRoleStmt(_) => todo!(),
            NodeEnum::DropRoleStmt(_) => todo!(),
            NodeEnum::LockStmt(_) => todo!(),
            NodeEnum::ConstraintsSetStmt(_) => todo!(),
            NodeEnum::ReindexStmt(_) => todo!(),
            NodeEnum::CheckPointStmt(_) => todo!(),
            NodeEnum::CreateSchemaStmt(n) => self.create_schema_stmt(n),
            NodeEnum::AlterDatabaseStmt(_) => todo!(),
            NodeEnum::AlterDatabaseRefreshCollStmt(_) => todo!(),
            NodeEnum::AlterDatabaseSetStmt(_) => todo!(),
            NodeEnum::AlterRoleSetStmt(_) => todo!(),
            NodeEnum::CreateConversionStmt(_) => todo!(),
            NodeEnum::CreateCastStmt(_) => todo!(),
            NodeEnum::CreateOpClassStmt(_) => todo!(),
            NodeEnum::CreateOpFamilyStmt(_) => todo!(),
            NodeEnum::AlterOpFamilyStmt(_) => todo!(),
            NodeEnum::PrepareStmt(_) => todo!(),
            NodeEnum::ExecuteStmt(n) => self.execute_stmt(n),
            NodeEnum::DeallocateStmt(_) => todo!(),
            NodeEnum::DeclareCursorStmt(_) => todo!(),
            NodeEnum::CreateTableSpaceStmt(_) => todo!(),
            NodeEnum::DropTableSpaceStmt(_) => todo!(),
            NodeEnum::AlterObjectDependsStmt(_) => todo!(),
            NodeEnum::AlterObjectSchemaStmt(_) => todo!(),
            NodeEnum::AlterOwnerStmt(_) => todo!(),
            NodeEnum::AlterOperatorStmt(_) => todo!(),
            NodeEnum::AlterTypeStmt(_) => todo!(),
            NodeEnum::DropOwnedStmt(_) => todo!(),
            NodeEnum::ReassignOwnedStmt(_) => todo!(),
            NodeEnum::CompositeTypeStmt(n) => self.composite_type_stmt(n),
            NodeEnum::CreateEnumStmt(_) => todo!(),
            NodeEnum::CreateRangeStmt(_) => todo!(),
            NodeEnum::AlterEnumStmt(_) => todo!(),
            NodeEnum::AlterTsdictionaryStmt(_) => todo!(),
            NodeEnum::AlterTsconfigurationStmt(_) => todo!(),
            NodeEnum::CreateFdwStmt(_) => todo!(),
            NodeEnum::AlterFdwStmt(_) => todo!(),
            NodeEnum::CreateForeignServerStmt(_) => todo!(),
            NodeEnum::AlterForeignServerStmt(_) => todo!(),
            NodeEnum::CreateUserMappingStmt(_) => todo!(),
            NodeEnum::AlterUserMappingStmt(_) => todo!(),
            NodeEnum::DropUserMappingStmt(_) => todo!(),
            NodeEnum::AlterTableSpaceOptionsStmt(_) => todo!(),
            NodeEnum::AlterTableMoveAllStmt(_) => todo!(),
            NodeEnum::SecLabelStmt(_) => todo!(),
            NodeEnum::CreateForeignTableStmt(n) => self.create_foreign_table_stmt(n),
            NodeEnum::ImportForeignSchemaStmt(_) => todo!(),
            NodeEnum::CreateExtensionStmt(n) => self.create_extension_stmt(n),
            NodeEnum::AlterExtensionStmt(_) => todo!(),
            NodeEnum::AlterExtensionContentsStmt(_) => todo!(),
            NodeEnum::CreateEventTrigStmt(_) => todo!(),
            NodeEnum::AlterEventTrigStmt(_) => todo!(),
            NodeEnum::RefreshMatViewStmt(_) => todo!(),
            NodeEnum::ReplicaIdentityStmt(_) => todo!(),
            NodeEnum::AlterSystemStmt(_) => todo!(),
            NodeEnum::CreatePolicyStmt(_) => todo!(),
            NodeEnum::AlterPolicyStmt(_) => todo!(),
            NodeEnum::CreateTransformStmt(_) => todo!(),
            NodeEnum::CreateAmStmt(_) => todo!(),
            NodeEnum::CreatePublicationStmt(_) => todo!(),
            NodeEnum::AlterPublicationStmt(_) => todo!(),
            NodeEnum::CreateSubscriptionStmt(_) => todo!(),
            NodeEnum::AlterSubscriptionStmt(_) => todo!(),
            NodeEnum::DropSubscriptionStmt(_) => todo!(),
            NodeEnum::CreateStatsStmt(_) => todo!(),
            NodeEnum::AlterCollationStmt(_) => todo!(),
            NodeEnum::CallStmt(_) => todo!(),
            NodeEnum::AlterStatsStmt(_) => todo!(),
            _ => unimplemented!("{:?}", n),
        }
    }
}
