name: CI

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: swatinem/rust-cache@v1
            - run: cargo fmt --check
            - run: cargo build --release --locked --all-features
            - run: cargo clippy --release --locked --all-features -- --deny warnings
            - run: cargo test --release --locked --all-features
